### ISSUE TITLE
Temat: Pseudokod [arkusz: obojętnie | język: obojętnie] 

### ISSUE THREAD

**Issue by JustlMax** [Pixel48/getLearn#4]
Przerabianie pseudokodów do matur, jak powinny wyglądać, na czym się skupiać, na co uważać i czego omijać. 
Np. czy przy zadaniu typu "napisz algorytm sortujący" stosowanie sortowania bąbelkowego obniży punkty na pseudokodzie?  
Dla mnie najlepiej w c++, ale w każdym innym też będzie dobrze, chodzi o fundament tego.
Pozdrawiam ^^ 
~JustMax

**Comment by Pixel48** [comment]
Pseudokod jest metodą opisywania logiki kodu, przez co jest bardziej porównywalny z mową niż z językiem programowania. W zasadzie, jeżeli czytając jakikolwiek kod mówisz pod nosem, co ten kod robi, to po zapisaniu tego powinieneś mieć prawidłowy pseudokod. Taka forma zapisu jest bardzo niesformalizowana i opiera się na opisywaniu np. w jaki sposób twój algorytm znajduje szukaną liczbę, lub w jaki sposób program przetwarza podane mu dane. Jeżeli na przykład mamy kod:
```cpp
int fib(int n) {
  if(n <= 2) return 1;
  else return fib(n-1) + fib(n-2);
}```
Po przełożeniu funkcji na pseudokod otrzymamy *coś na kształt tego*:
```
n <- n-ta liczba Ciągu Fibonacciego (całkowita)
**Jeżeli** n mniejsze lub równe 2: **zwróć** 1
**W przeciwnym wypadku**: **zwróć** fib(n-1) + fib(n-2)
```
W praktyce pseudokod to schemat działania kodu, na podstawie którego można napisać kod, lub samodzielnie wykonać krok po kroku

**Comment by JustlMax** [comment]
Dzięki bardzo za odpowiedź, trochę mi to rozjaśniło ^^
