### ISSUE TITLE
Arkusz 7 czerwca 2019 r.

### ISSUE THREAD

**Issue by wernexnrs** [Pixel48/getLearn#7]
Zadanie 5. Zbiornik wody EXCEL
Zadanie 1 z podpunktami częsci teoretycznej - rekurencja

Tłumaczenie, którego nie ogarniam - [https://www.youtube.com/watch?v=8pCX431e-OE&ab_channel=BarbaraFeluch](url)
Link do arkusza i danych - [https://arkusze.pl/matura-informatyka-2019-czerwiec-poziom-rozszerzony/](url)

Przydałby się live na DC

**Comment by Pixel48** [comment]
Z tego co widzę, to o ile zadanie ze zbiornikiem wody polega w zasadzie na przepisaniu podanych zasad z polskiego na matematyczno-tabelaryczny excela, to pierwsze wymaga trochę więcej zaangażowania. Możemy ugadać jakiś live, myślę, że poniedziałek jest całkiem obiecujący

**Comment by Pixel48** [comment]
Dzisiaj na [Do Matury}(https://disboard.org/pl/server/796048059507015732) o 18:30 będziemy przerabiać ten arkusz. [Zparaszam](https://discord.com/channels/796048059507015732/804293590754131998/843439803017592852)
